---
version: 0.5.0
slug: open3e
name: Open3e
description: Connect to E3 Controls through CAN
url: https://github.com/flecke-m/ha-addons/tree/main/open3e
codenotary: big.dog@gmx.net
arch:
  - amd64
  - armhf
  - aarch64
hassio_api: true
host_network: true
image: "fleckem/ha-addon-open3e-{arch}"
init: false
options: {
  "configurations": {
    "can": "can0",
    "Listen_Topic": "open3e/cmnd"
    "Server_Topic": "open3e",
    "MQTT_FormatString": "{device}_{ecuAddr:03X}_{didNumber}_{didName}",
    "MQTT_ClientID": "open3e"
  }
}
privileged:
  - NET_ADMIN
schema: {
  "configurations": {
      "can": "str",
      "Listen_Topic": "str"
      "Server_Topic": "str",
      "MQTT_FormatString": "str",
      "MQTT_ClientID": "str"
  }
}
services:
  - mqtt:need
startup: services
